#!/bin/bash

# Script para diagnosticar el error de autorización de Strava

echo "🔍 Diagnosticando Error de Autorización de Strava"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣ Verificando redirect_uri usado en la app..."
echo ""
echo "   Redirect URI en la app:"
echo "   https://uprohtkbghujvjwjnqyv.supabase.co/functions/v1/strava-auth"
echo ""

echo "2️⃣ Verificando configuración necesaria en Strava..."
echo ""
echo "   ⚠️  IMPORTANTE: El redirect_uri DEBE estar configurado en Strava"
echo ""
echo "   Ve a: https://www.strava.com/settings/api"
echo "   Haz clic en tu aplicación 'BeRun'"
echo "   Busca 'Authorization Callback Domain' o 'Redirect URI'"
echo "   Debe incluir:"
echo "   • https://uprohtkbghujvjwjnqyv.supabase.co"
echo "   O específicamente:"
echo "   • https://uprohtkbghujvjwjnqyv.supabase.co/functions/v1/strava-auth"
echo ""

echo "3️⃣ Verificando variables de entorno en Supabase..."
echo ""
echo "   Ve a: https://supabase.com/dashboard/project/uprohtkbghujvjwjnqyv/settings/functions"
echo "   Verifica que existan estas variables:"
echo ""
echo "   ✅ STRAVA_CLIENT_ID = 186314"
echo "   ✅ STRAVA_CLIENT_SECRET = fa541a582f6dde856651e09cb546598865b000b15"
echo "   ✅ STRAVA_WEBHOOK_VERIFY_TOKEN = berun_webhook_verify_2024"
echo ""

echo "4️⃣ Verificando logs de la Edge Function..."
echo ""
echo "   Ve a: https://supabase.com/dashboard/project/uprohtkbghujvjwjnqyv/functions"
echo "   Haz clic en 'strava-auth'"
echo "   Ve a la pestaña 'Logs'"
echo "   Busca errores relacionados con:"
echo "   • Missing environment variables"
echo "   • STRAVA_CLIENT_SECRET"
echo "   • Token exchange failed"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 POSIBLES CAUSAS DEL ERROR:"
echo ""
echo "1. ❌ Redirect URI no configurado en Strava"
echo "   → Solución: Configurar en Strava Dashboard"
echo ""
echo "2. ❌ Variables de entorno no configuradas"
echo "   → Solución: Configurar en Supabase Dashboard"
echo ""
echo "3. ❌ Client Secret incorrecto o no configurado"
echo "   → Solución: Verificar en Supabase y Strava"
echo ""
echo "4. ❌ Código de autorización ya usado o expirado"
echo "   → Solución: Intentar conectar de nuevo"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ PASOS PARA SOLUCIONAR:"
echo ""
echo "PASO 1: Configurar Redirect URI en Strava"
echo "─────────────────────────────────────────────"
echo "1. Ve a: https://www.strava.com/settings/api"
echo "2. Haz clic en 'BeRun'"
echo "3. Busca 'Authorization Callback Domain'"
echo "4. Añade: uprohtkbghujvjwjnqyv.supabase.co"
echo "5. O el URI completo si lo requiere"
echo "6. Guarda los cambios"
echo ""
echo "PASO 2: Verificar Variables de Entorno"
echo "─────────────────────────────────────────────"
echo "1. Ve a: https://supabase.com/dashboard/project/uprohtkbghujvjwjnqyv/settings/functions"
echo "2. Verifica que existan las 3 variables mencionadas arriba"
echo "3. Si no existen, créalas"
echo ""
echo "PASO 3: Revisar Logs"
echo "─────────────────────────────────────────────"
echo "1. Ve a los logs de strava-auth"
echo "2. Intenta conectar de nuevo"
echo "3. Revisa los mensajes de error específicos"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

